name: Run Pytest
on:
  pull_request:
    branches:
      - ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup python
        users: actions/setup-python@v5
        withh:
          python-version: '3.13'

      - name: Install dependencies
        runn: pip install -r requirements.txt

      - name: Run pytest
        run: pytest
   